# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(601, 10, 431, 111))
        self.groupBox.setObjectName("groupBox")
        self.splitter_9 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_9.setGeometry(QtCore.QRect(10, 25, 191, 71))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label = QtWidgets.QLabel(self.splitter_7)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.splitter_7)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.lip = QtWidgets.QLineEdit(self.splitter_5)
        self.lip.setObjectName("lip")
        self.rip = QtWidgets.QLineEdit(self.splitter_5)
        self.rip.setText("")
        self.rip.setObjectName("rip")
        self.splitter_10 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_10.setGeometry(QtCore.QRect(210, 25, 121, 71))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.label_2 = QtWidgets.QLabel(self.splitter_8)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_8)
        self.label_7.setObjectName("label_7")
        self.splitter = QtWidgets.QSplitter(self.splitter_10)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.lport = QtWidgets.QLineEdit(self.splitter)
        self.lport.setObjectName("lport")
        self.rport = QtWidgets.QLineEdit(self.splitter)
        self.rport.setText("")
        self.rport.setObjectName("rport")
        self.splitter_11 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_11.setGeometry(QtCore.QRect(340, 24, 81, 73))
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.ltest = QtWidgets.QPushButton(self.splitter_11)
        self.ltest.setObjectName("ltest")
        self.rtest = QtWidgets.QPushButton(self.splitter_11)
        self.rtest.setObjectName("rtest")
        self.send_data = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.send_data.setGeometry(QtCore.QRect(10, 30, 581, 424))
        self.send_data.setObjectName("send_data")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(11, 9, 81, 16))
        self.label_3.setObjectName("label_3")
        self.Receive_data = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Receive_data.setGeometry(QtCore.QRect(11, 480, 581, 201))
        self.Receive_data.setObjectName("Receive_data")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(13, 460, 141, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 130, 141, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 20, 111, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.open = QtWidgets.QPushButton(self.layoutWidget)
        self.open.setObjectName("open")
        self.gridLayout_2.addWidget(self.open, 0, 0, 1, 1)
        self.connect = QtWidgets.QPushButton(self.layoutWidget)
        self.connect.setObjectName("connect")
        self.gridLayout_2.addWidget(self.connect, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(890, 130, 141, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.splitter_14 = QtWidgets.QSplitter(self.groupBox_4)
        self.splitter_14.setGeometry(QtCore.QRect(10, 20, 48, 61))
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName("splitter_14")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(15, 20, 111, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.close = QtWidgets.QPushButton(self.layoutWidget_2)
        self.close.setObjectName("close")
        self.gridLayout_3.addWidget(self.close, 2, 0, 1, 1)
        self.send = QtWidgets.QPushButton(self.layoutWidget_2)
        self.send.setObjectName("send")
        self.gridLayout_3.addWidget(self.send, 1, 0, 1, 1)
        self.debugger = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.debugger.setGeometry(QtCore.QRect(600, 270, 431, 411))
        self.debugger.setReadOnly(True)
        self.debugger.setObjectName("debugger")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(602, 248, 81, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(600, 130, 111, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.splitter_12 = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter_12.setGeometry(QtCore.QRect(27, 31, 71, 61))
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.radio_tcp = QtWidgets.QRadioButton(self.splitter_12)
        self.radio_tcp.setObjectName("radio_tcp")
        self.radio_udp = QtWidgets.QRadioButton(self.splitter_12)
        self.radio_udp.setObjectName("radio_udp")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(590, -650, 0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(590, -650, 0, 0))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(590, -650, 0, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(590, -650, 0, 0))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lip, self.lport)
        MainWindow.setTabOrder(self.lport, self.ltest)
        MainWindow.setTabOrder(self.ltest, self.rip)
        MainWindow.setTabOrder(self.rip, self.rport)
        MainWindow.setTabOrder(self.rport, self.rtest)
        MainWindow.setTabOrder(self.rtest, self.send_data)
        MainWindow.setTabOrder(self.send_data, self.radio_tcp)
        MainWindow.setTabOrder(self.radio_tcp, self.radio_udp)
        MainWindow.setTabOrder(self.radio_udp, self.open)
        MainWindow.setTabOrder(self.open, self.connect)
        MainWindow.setTabOrder(self.connect, self.send)
        MainWindow.setTabOrder(self.send, self.close)
        MainWindow.setTabOrder(self.close, self.Receive_data)
        MainWindow.setTabOrder(self.Receive_data, self.debugger)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络调试工具 by 浅笑996"))
        self.groupBox.setTitle(_translate("MainWindow", "IP配置"))
        self.label.setText(_translate("MainWindow", "本地IP"))
        self.label_8.setText(_translate("MainWindow", "远程IP"))
        self.label_2.setText(_translate("MainWindow", "本地端口"))
        self.label_7.setText(_translate("MainWindow", "远程端口"))
        self.ltest.setText(_translate("MainWindow", "测试占用"))
        self.rtest.setText(_translate("MainWindow", "测试连通"))
        self.label_3.setText(_translate("MainWindow", "Send Data"))
        self.label_4.setText(_translate("MainWindow", "Receive Data"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Connect"))
        self.open.setText(_translate("MainWindow", "开启监听"))
        self.connect.setText(_translate("MainWindow", "连接远端"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Common"))
        self.close.setText(_translate("MainWindow", "关闭连接"))
        self.send.setText(_translate("MainWindow", "发送数据"))
        self.label_5.setText(_translate("MainWindow", "Debugger"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Agreement"))
        self.radio_tcp.setText(_translate("MainWindow", "TCP"))
        self.radio_udp.setText(_translate("MainWindow", "UDP"))

